##############################################################################
#####            Random Survival Forests with Competing Events:          #####
#####            A Subdistribution-Based Imputation Approach             #####
#####                        Electronic Supplement                       #####
##############################################################################
#####             Author: Charlotte Behning                              #####
##############################################################################
#####             Content: R-Code of the Simulations                     #####
#####                      presented in Section 3                        ##### 
##############################################################################


# This document provides a description on how to access the other files in the 
# repository. Following the Readme allows to replicate the simulation results of
# Random Survival Forests with Competing Events: A Subdistribution-Based Imputation Approach

# Note: For confidentiality reasons, the application data has not been provided.


# 1. 
# "functions_data_generating.R"
# contains functions to run the remaining code

# 2.
# "data_generation.R"
# generates the input data for the simulations.
# in this example, it will only be created for 1 seed

# 3. "train_predict.R"
# gives detailed information on how to compile ranger and how to run the 
# training and prediction.
# prediction results for 1 simulation run are available in the repository and can be
# extracted using
untar("pred_setup1.tar.gz")
# also, example output to create the illustration figure of G are included here.


# 4. "preprocessing_results.R"
# contains all processing steps to gather simulation results in the required format
# for plotting. It can be executed after getting the folder pred_setup1, but only for
# one simulation run of setup1. The data generated by 1000 repeats of the simulation 
# are provided as summary statistics in this repository.

#"<setup>_status_freq.rda" contains status frequencies of all runs.
#"<setup>_importance.rda" contains all VIMP measures.
#"<setup>_results_data.rda" contains summary statistics needed to create all figure and tables

# "5. evaluation.R"
# created all figures and tables of the simulation results as presented in the manuscript
# or the supplement











